language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - brew tap manastech/crystal
  - brew update
  - brew install crystal-lang

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
